import type { SymbolName } from '@/db/types';

export const HABIT_COLORS: string[] = [
  '#FF453A',
  '#FF6B35',
  '#FF9F0A',
  '#FFD60A',
  '#30D158',
  '#00B894',
  '#0FB9B1',
  '#64D2FF',
  '#0A84FF',
  '#5E5CE6',
  '#A29BFE',
  '#BF5AF2',
  '#FF375F',
  '#FD79A8',
];

export const HABIT_ICONS: SymbolName[] = [
  'figure.run',
  'figure.walk',
  'figure.strengthtraining.traditional',
  'figure.yoga',
  'dumbbell.fill',
  'bicycle',
  'drop.fill',
  'cup.and.saucer.fill',
  'fork.knife',
  'leaf.fill',
  'bed.double.fill',
  'moon.stars.fill',
  'sun.max.fill',
  'book.fill',
  'pencil',
  'graduationcap.fill',
  'guitars.fill',
  'music.note',
  'paintpalette.fill',
  'camera.fill',
  'gamecontroller.fill',
  'brain.head.profile',
  'heart.fill',
  'pills.fill',
  'cross.case.fill',
  'sparkles',
  'star.fill',
  'flame.fill',
  'bolt.fill',
  'trophy.fill',
  'flag.fill',
  'checkmark.circle.fill',
  'hands.sparkles.fill',
  'bubble.left.fill',
  'phone.fill',
  'envelope.fill',
  'dollarsign.circle.fill',
  'cart.fill',
  'house.fill',
  'pawprint.fill',
];

export const DEFAULT_COLOR = HABIT_COLORS[4];
export const DEFAULT_ICON: SymbolName = HABIT_ICONS[0];
